	drop database if exists SolucionesEficientes;
create database SolucionesEficientes;
use SolucionesEficientes;

DROP TABLE IF EXISTS CLIENTE;
CREATE TABLE CLIENTE(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
REPRESENTANTE VARCHAR(50) NOT NULL,
CORREO VARCHAR(80) NOT NULL,
TELEFONO BIGINT NOT NULL unique,
DIRECCION VARCHAR(50) NOT NULL,
SECTOR ENUM("Tecnologia","Salud","Educacion","Comercio","Manofactura")
);

 DROP TABLE IF EXISTS SERVICIO;
 CREATE TABLE SERVICIO(
 ID INT PRIMARY KEY AUTO_INCREMENT,
 NOMBRE VARCHAR(50) NOT NULL,
 DESCRIPCION VARCHAR(50) NOT NULL,
 PRECIOPORHORA DECIMAL(10,2) NOT NULL,
 CATEGORIA ENUM("TI","Limpieza","Seguridad","Administracion")
 );
 
DROP TABLE IF EXISTS CONTRATO;
CREATE TABLE CONTRATO(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_CLIENTE INT,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID),
ID_SERVICIO INT ,
FOREIGN KEY(ID_SERVICIO) REFERENCES SERVICIO(ID),
FECHA_INICIO DATE NOT NULL,
FECHA_FIN DATE NOT NULL,
COSTO_TOTAL DECIMAL(10,2) NOT NULL,
ESTADO ENUM("Activo","En_espera","Finalizado")
);


DROP TABLE IF EXISTS PROYECTO;
CREATE TABLE PROYECTO(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_CLIENTE INT,
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID),
NOMBRE VARCHAR(50) NOT NULL,
FECHA_INICIO DATE NOT NULL,
FECHA_FIN DATE NOT NULL,
ESTADO ENUM("En_curso","Completado","Cancelado")
);


DROP TABLE IF EXISTS EMPLEADO;
CREATE TABLE EMPLEADO(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
CARGO VARCHAR(50) NOT NULL,
SALARIO DECIMAL(10,2) NOT NULL,
ESPECIALIDAD ENUM("TI","Administracion","Limpieza","Seguridad"),
ID_PROYECTO INT,
FOREIGN KEY(ID_PROYECTO) REFERENCES PROYECTO(ID)
);

DROP TABLE IF EXISTS ASIGNACION;
CREATE TABLE ASIGNACION(
ID_EMPLEADO INT PRIMARY KEY,
FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID),
ID_PROYECTO INT,
FOREIGN KEY(ID_PROYECTO) REFERENCES PROYECTO(ID),
HORAS_TRABAJADAS INT NOT NULL,
FECHA_ASIGNACION DATE NOT NULL
);































